clear all;close all;clc

plot_ls = false;

load('MU_MMIMO_M_100_K_10_Np_37_BER_comparison_mp_ls_equalization_mmse_pilots_bpsk_v20_20151208T001253.mat');


% Plot frequency domain estimation error for each one of the techniques.
fdee_figure = figure; grid on; hold on;
xlabel('Eb/No [dB]');ylabel('MSE');
title('Estimation Error');

if(plot_ls)
    semilogy(EbNoVec, error_fd_ls, 'ks', ...
        EbNoVec, error_fd_mmse, 'bs', ...
        EbNoVec, error_fd_gaels, 'k*', ...
        EbNoVec, error_fd_els, 'ko', ...
        EbNoVec, error_fd_omp, 'ro', ...
        EbNoVec, error_fd_cosamp, 'rs', ...
        EbNoVec, error_fd_mp, 'gs');
    legend('LS', 'MMSE', 'GA-MP-LS', 'MP-LS', 'OMP', 'COSAMP', 'MP');
    semilogy(EbNoVec, error_fd_ls, 'k-', EbNoVec, error_fd_mmse, 'b-', EbNoVec, error_fd_gaels, 'k-', EbNoVec, error_fd_els, 'k-', EbNoVec, error_fd_omp, 'r-', EbNoVec, error_fd_cosamp, 'r-', EbNoVec, error_fd_mp, 'g-');
    hold off
else
    semilogy(EbNoVec, error_fd_mmse, 'bs', ...
        EbNoVec, error_fd_gaels, 'k*', ...
        EbNoVec, error_fd_els, 'ko', ...
        EbNoVec, error_fd_omp, 'ro', ...
        EbNoVec, error_fd_cosamp, 'rs', ...
        EbNoVec, error_fd_mp, 'gs');
    legend('MMSE', 'GA-MP-LS', 'MP-LS', 'OMP', 'COSAMP', 'MP');
    semilogy(EbNoVec, error_fd_mmse, 'b-', EbNoVec, error_fd_gaels, 'k-', EbNoVec, error_fd_els, 'k-', EbNoVec, error_fd_omp, 'r-', EbNoVec, error_fd_cosamp, 'r-', EbNoVec, error_fd_mp, 'g-');
    hold off
end